package erp.ws.sbo.client.swing.model;
// Generated Jul 14, 2013 5:55:40 PM by Hibernate Tools 3.4.0.CR1



/**
 * @asn1 generated by hbm2java
 */
public class asn1  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -1688741078329309868L;
	private asn1Id id;
     private pasn pasn;
     private Integer visOrder;
     private Integer object;
     private Integer logInst;
     private String USn;
     private String UMemo;

    public asn1() {
    }

	
    public asn1(asn1Id id, pasn pasn, String USn) {
        this.id = id;
        this.pasn = pasn;
        this.USn = USn;
    }
    public asn1(asn1Id id, pasn pasn, Integer visOrder, Integer object, Integer logInst, String USn, String UMemo) {
       this.id = id;
       this.pasn = pasn;
       this.visOrder = visOrder;
       this.object = object;
       this.logInst = logInst;
       this.USn = USn;
       this.UMemo = UMemo;
    }
   
    public asn1Id getId() {
        return this.id;
    }
    
    public void setId(asn1Id id) {
        this.id = id;
    }
    public pasn getpasn() {
        return this.pasn;
    }
    
    public void setpasn(pasn pasn) {
        this.pasn = pasn;
    }
    public Integer getVisOrder() {
        return this.visOrder;
    }
    
    public void setVisOrder(Integer visOrder) {
        this.visOrder = visOrder;
    }
    public Integer getObject() {
        return this.object;
    }
    
    public void setObject(Integer object) {
        this.object = object;
    }
    public Integer getLogInst() {
        return this.logInst;
    }
    
    public void setLogInst(Integer logInst) {
        this.logInst = logInst;
    }
    public String getUSn() {
        return this.USn;
    }
    
    public void setUSn(String USn) {
        this.USn = USn;
    }
    public String getUMemo() {
        return this.UMemo;
    }
    
    public void setUMemo(String UMemo) {
        this.UMemo = UMemo;
    }




}


