package erp.ws.sbo.client.swing.model;

// Generated 2014-3-29 19:39:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UQrm generated by hbm2java
 */
public class UQrm implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6323306964008053525L;
	private int docEntry;
	private int docNum;
	private Integer period;
	private Date docDate;
	private Short instance;
	private Integer series;
	private String handwrtten;
	private String canceled;
	private Integer object;
	private Integer logInst;
	private Integer userSign;
	private String transfered;
	private String status;
	private Date createDate;
	private Short createTime;
	private Date updateDate;
	private Short updateTime;
	private String dataSource;
	private String printed;
	private int rdocEntry;
	private boolean ifR;
	private String subuid;
	private String cardCode;
	private String cardName;
	private Integer cntctCode;
	private Integer slpCode;
	private Integer USlpCode1;
	private String UDq;
	private String comments;
	
	private Set<URm1> URm1s = new HashSet<URm1>(0);

	public UQrm() {
	}

	public UQrm(int docEntry, int docNum, Date createDate, Date updateDate,
			int rdocEntry, boolean ifR, String subuid,
			String cardCode, String cardName) {
		this.docEntry = docEntry;
		this.docNum = docNum;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.rdocEntry = rdocEntry;
		this.ifR = ifR;
		this.subuid = subuid;
		this.cardCode = cardCode;
		this.cardName = cardName;
	}

	public UQrm(int docEntry, int docNum, Integer period, Date docDate, Short instance,
			Integer series, String handwrtten, String canceled, Integer object,
			Integer logInst, Integer userSign, String transfered,
			String status, Date createDate, Short createTime, Date updateDate,
			Short updateTime, String dataSource, String printed,int rdocEntry, boolean ifR,
			String subuid, String cardCode, String cardName,Integer CntctCode,
			Integer sqlCode, Integer USqlCode1, String UDq,String comments,Set<URm1> URm1s) {
		this.docEntry = docEntry;
		this.docNum = docNum;
		this.period = period;
		this.docDate=docDate;
		this.instance = instance;
		this.series = series;
		this.handwrtten = handwrtten;
		this.canceled = canceled;
		this.object = object;
		this.logInst = logInst;
		this.userSign = userSign;
		this.transfered = transfered;
		this.status = status;
		this.createDate = createDate;
		this.createTime = createTime;
		this.updateDate = updateDate;
		this.updateTime = updateTime;
		this.dataSource = dataSource;
		this.printed=printed;
		this.rdocEntry = rdocEntry;
		this.ifR = ifR;
		this.subuid = subuid;
		this.cardCode = cardCode;
		this.cardName = cardName;
		this.cntctCode=CntctCode;
		this.slpCode = sqlCode;
		this.USlpCode1 = USqlCode1;
		this.UDq=UDq;
		this.comments=comments;
		this.setURm1s(URm1s);
	}

	public int getDocEntry() {
		return this.docEntry;
	}

	public void setDocEntry(int docEntry) {
		this.docEntry = docEntry;
	}

	public int getDocNum() {
		return this.docNum;
	}

	public void setDocNum(int docNum) {
		this.docNum = docNum;
	}

	public Integer getPeriod() {
		return this.period;
	}

	public void setPeriod(Integer period) {
		this.period = period;
	}

	public Date getDocDate() {
		return docDate;
	}

	public void setDocDate(Date docDate) {
		this.docDate = docDate;
	}

	public Short getInstance() {
		return this.instance;
	}

	public void setInstance(Short instance) {
		this.instance = instance;
	}

	public Integer getSeries() {
		return this.series;
	}

	public void setSeries(Integer series) {
		this.series = series;
	}

	public String getHandwrtten() {
		return this.handwrtten;
	}

	public void setHandwrtten(String handwrtten) {
		this.handwrtten = handwrtten;
	}

	public String getCanceled() {
		return this.canceled;
	}

	public void setCanceled(String canceled) {
		this.canceled = canceled;
	}

	public Integer getObject() {
		return this.object;
	}

	public void setObject(Integer object) {
		this.object = object;
	}

	public Integer getLogInst() {
		return this.logInst;
	}

	public void setLogInst(Integer logInst) {
		this.logInst = logInst;
	}

	public Integer getUserSign() {
		return this.userSign;
	}

	public void setUserSign(Integer userSign) {
		this.userSign = userSign;
	}

	public String getTransfered() {
		return this.transfered;
	}

	public void setTransfered(String transfered) {
		this.transfered = transfered;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Short getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Short createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Short getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Short updateTime) {
		this.updateTime = updateTime;
	}

	public String getDataSource() {
		return this.dataSource;
	}

	public void setDataSource(String dataSource) {
		this.dataSource = dataSource;
	}

	public String getPrinted() {
		return printed;
	}

	public void setPrinted(String printed) {
		this.printed = printed;
	}

	public int getRdocEntry() {
		return this.rdocEntry;
	}

	public void setRdocEntry(int rdocEntry) {
		this.rdocEntry = rdocEntry;
	}

	public boolean isIfR() {
		return this.ifR;
	}

	public void setIfR(boolean ifR) {
		this.ifR = ifR;
	}

	public String getSubuid() {
		return this.subuid;
	}

	public void setSubuid(String subuid) {
		this.subuid = subuid;
	}

	public String getCardCode() {
		return this.cardCode;
	}

	public void setCardCode(String cardCode) {
		this.cardCode = cardCode;
	}

	public String getCardName() {
		return this.cardName;
	}

	public void setCardName(String cardName) {
		this.cardName = cardName;
	}

	public Integer getCntctCode() {
		return cntctCode;
	}

	public void setCntctCode(Integer cntctCode) {
		this.cntctCode = cntctCode;
	}

	public Integer getSlpCode() {
		return this.slpCode;
	}

	public void setSlpCode(Integer sqlCode) {
		this.slpCode = sqlCode;
	}

	public Integer getUSlpCode1() {
		return this.USlpCode1;
	}

	public void setUSlpCode1(Integer USqlCode1) {
		this.USlpCode1 = USqlCode1;
	}

	public String getUDq() {
		return UDq;
	}

	public void setUDq(String uDq) {
		UDq = uDq;
	}

	public String getComments() {
		return comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Set<URm1> getURm1s() {
		return this.URm1s;
	}

	public void setURm1s(Set<URm1> URm1s) {
		this.URm1s = URm1s;
	}

}
