package erp.ws.sbo.client.swing.model;

// Generated 2014-3-29 19:39:50 by Hibernate Tools 3.4.0.CR1

/**
 * URm1Id generated by hbm2java
 */
public class URm1Id implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5993451591185469464L;
	private UQrm docEntry;
	private int lineId;

	public URm1Id() {
	}

	public URm1Id(UQrm docEntry, int lineId) {
		this.docEntry = docEntry;
		this.lineId = lineId;
	}

	public UQrm getDocEntry() {
		return this.docEntry;
	}

	public void setDocEntry(UQrm docEntry) {
		this.docEntry = docEntry;
	}

	public int getLineId() {
		return this.lineId;
	}

	public void setLineId(int lineId) {
		this.lineId = lineId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof URm1Id))
			return false;
		URm1Id castOther = (URm1Id) other;

		return (this.getDocEntry() == castOther.getDocEntry())
				&& (this.getLineId() == castOther.getLineId());
	}

	public int hashCode() {
		int result = 17;

		 result = 37 * result + ( getDocEntry() == null ? 0 : this.getDocEntry().hashCode() );
		result = 37 * result + this.getLineId();
		return result;
	}

}
