package erp.ws.sbo.client.swing.model;
// Generated Jul 14, 2013 5:55:40 PM by Hibernate Tools 3.4.0.CR1



/**
 * @asn1Id generated by hbm2java
 */
public class asn1Id  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 3125858679358780148L;
	private pasn docEntry;
     private Integer lineId;

    public asn1Id() {
    }

    public asn1Id(pasn docEntry, int lineId) {
       this.docEntry = docEntry;
       this.lineId = lineId;
    }
   
    public pasn getDocEntry() {
        return this.docEntry;
    }
    
    public void setDocEntry(pasn docEntry) {
        this.docEntry = docEntry;
    }
    public Integer getLineId() {
        return this.lineId;
    }
    
    public void setLineId(Integer lineId) {
        this.lineId = lineId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof asn1Id) ) return false;
		 asn1Id castOther = ( asn1Id ) other; 
         
		 return (this.getDocEntry()==castOther.getDocEntry())
 && (this.getLineId()==castOther.getLineId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDocEntry() == null ? 0 : this.getDocEntry().hashCode() );
         result = 37 * result + ( getLineId() == null ? 0 : this.getLineId().hashCode() );
         return result;
   }   


}


