package erp.ws.sbo.client.swing.model;
// Generated Jul 4, 2013 10:25:54 PM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;

/**
 * @desn generated by hbm2java
 */
public class desn  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -47292355966273358L;
	private int id;
     private boolean ifdraft;
     private int objType;
     private int docEntry;
     private int lineNum;
     private String itemcode;
     private BigDecimal length;
     private String sn;
     private BigDecimal weight;
     private String direction;
     private boolean ifPaSn;
     private String paSn;
     private String wareHouse;
     private String cardCode;
     private String memo;
     private String workCenter;
     private Date cdatetime;
     private Date udatetime;

    public desn() {
    }

	
    public desn(int id, boolean ifdraft, int objType, int docEntry, int lineNum, String itemcode, BigDecimal length, String sn, BigDecimal weight, String direction, boolean ifPaSn, Date cdatetime, Date udatetime) {
        this.id = id;
        this.ifdraft = ifdraft;
        this.objType = objType;
        this.docEntry = docEntry;
        this.lineNum = lineNum;
        this.itemcode = itemcode;
        this.length = length;
        this.sn = sn;
        this.weight = weight;
        this.direction = direction;
        this.ifPaSn = ifPaSn;
        this.cdatetime = cdatetime;
        this.udatetime = udatetime;
    }
    public desn(int id, boolean ifdraft, int objType, int docEntry, int lineNum, String itemcode, BigDecimal length, String sn, BigDecimal weight, String direction, boolean ifPaSn, String paSn, String wareHouse, String cardCode, String memo, String workCenter, Date cdatetime, Date udatetime) {
       this.id = id;
       this.ifdraft = ifdraft;
       this.objType = objType;
       this.docEntry = docEntry;
       this.lineNum = lineNum;
       this.itemcode = itemcode;
       this.length = length;
       this.sn = sn;
       this.weight = weight;
       this.direction = direction;
       this.ifPaSn = ifPaSn;
       this.paSn = paSn;
       this.wareHouse = wareHouse;
       this.cardCode = cardCode;
       this.memo = memo;
       this.workCenter = workCenter;
       this.cdatetime = cdatetime;
       this.udatetime = udatetime;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public boolean isIfdraft() {
        return this.ifdraft;
    }
    
    public void setIfdraft(boolean ifdraft) {
        this.ifdraft = ifdraft;
    }
    public int getObjType() {
        return this.objType;
    }
    
    public void setObjType(int objType) {
        this.objType = objType;
    }
    public int getDocEntry() {
        return this.docEntry;
    }
    
    public void setDocEntry(int docEntry) {
        this.docEntry = docEntry;
    }
    public int getLineNum() {
        return this.lineNum;
    }
    
    public void setLineNum(int lineNum) {
        this.lineNum = lineNum;
    }
    public String getItemcode() {
        return this.itemcode;
    }
    
    public void setItemcode(String itemcode) {
        this.itemcode = itemcode;
    }
    public BigDecimal getLength() {
        return this.length;
    }
    
    public void setLength(BigDecimal length) {
        this.length = length;
    }
    public String getSn() {
        return this.sn;
    }
    
    public void setSn(String sn) {
        this.sn = sn;
    }
    public BigDecimal getWeight() {
        return this.weight;
    }
    
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }
    public String getDirection() {
        return this.direction;
    }
    
    public void setDirection(String direction) {
        this.direction = direction;
    }
    public boolean isIfPaSn() {
        return this.ifPaSn;
    }
    
    public void setIfPaSn(boolean ifPaSn) {
        this.ifPaSn = ifPaSn;
    }
    public String getPaSn() {
        return this.paSn;
    }
    
    public void setPaSn(String paSn) {
        this.paSn = paSn;
    }
    public String getWareHouse() {
        return this.wareHouse;
    }
    
    public void setWareHouse(String wareHouse) {
        this.wareHouse = wareHouse;
    }
    public String getCardCode() {
        return this.cardCode;
    }
    
    public void setCardCode(String cardCode) {
        this.cardCode = cardCode;
    }
    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }
    public String getWorkCenter() {
        return this.workCenter;
    }
    
    public void setWorkCenter(String workCenter) {
        this.workCenter = workCenter;
    }
    public Date getCdatetime() {
        return this.cdatetime;
    }
    
    public void setCdatetime(Date cdatetime) {
        this.cdatetime = cdatetime;
    }
    public Date getUdatetime() {
        return this.udatetime;
    }
    
    public void setUdatetime(Date udatetime) {
        this.udatetime = udatetime;
    }




}


