package erp.ws.sbo.client.swing.model;

// Generated 2014-3-29 19:39:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * URm1 generated by hbm2java
 */
public class URm1 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2009288018249695827L;
	private URm1Id id;
	private UQrm UQrm;
	private Integer visOrder;
	private Integer object;
	private Integer logInst;
	private String itemCode;
	private String itemName;
	private String UYmd;
	private BigDecimal ULength;
	private String unitMsr;
	private BigDecimal numPerMsr;
	private int UGs;
	private BigDecimal UGjjg;
	private BigDecimal quantity;
	private BigDecimal price;
	private BigDecimal UMjg;
	private BigDecimal linetotal;
	private String issue;
	private String result;
	private String dalloc;
	private String resP;
	private String proRes;
	private String impmeas;
	private String memo;

	public URm1() {
	}

	public URm1(URm1Id id, UQrm UQrm, String itemCode, String itemName,
			String UYmd, BigDecimal ULength, int UGs,
			BigDecimal quantity, BigDecimal price, BigDecimal UMjg,
			BigDecimal linetotal) {
		this.id = id;
		this.UQrm = UQrm;
		this.itemCode = itemCode;
		this.itemName = itemName;
		this.UYmd = UYmd;
		this.ULength = ULength;
		this.UGs = UGs;
		this.quantity = quantity;
		this.price = price;
		this.UMjg = UMjg;
		this.linetotal = linetotal;
	}

	public URm1(URm1Id id, UQrm UQrm, Integer visOrder, Integer object,
			Integer logInst, String itemCode, String itemName,
			String UYmd, BigDecimal ULength, String unitMsr,BigDecimal numPerMsr,int UGs,
			BigDecimal UGjjg,BigDecimal quantity, BigDecimal price, BigDecimal UMjg,
			BigDecimal linetotal, String issue, String result,
			String dalloc, String resP, String proRes,
			String impmeas, String memo) {
		this.id = id;
		this.UQrm = UQrm;
		this.visOrder = visOrder;
		this.object = object;
		this.logInst = logInst;
		this.itemCode = itemCode;
		this.itemName = itemName;
		this.UYmd = UYmd;
		this.ULength = ULength;
		this.unitMsr=unitMsr;
		this.numPerMsr=numPerMsr;
		this.UGs = UGs;
		this.UGjjg=UGjjg;
		this.quantity = quantity;
		this.price = price;
		this.UMjg = UMjg;
		this.linetotal = linetotal;
		this.issue = issue;
		this.result = result;
		this.dalloc = dalloc;
		this.resP = resP;
		this.proRes = proRes;
		this.impmeas = impmeas;
		this.memo = memo;
	}

	public URm1Id getId() {
		return this.id;
	}

	public void setId(URm1Id id) {
		this.id = id;
	}

	public UQrm getUQrm() {
		return this.UQrm;
	}

	public void setUQrm(UQrm UQrm) {
		this.UQrm = UQrm;
	}

	public Integer getVisOrder() {
		return this.visOrder;
	}

	public void setVisOrder(Integer visOrder) {
		this.visOrder = visOrder;
	}

	public Integer getObject() {
		return this.object;
	}

	public void setObject(Integer object) {
		this.object = object;
	}

	public Integer getLogInst() {
		return this.logInst;
	}

	public void setLogInst(Integer logInst) {
		this.logInst = logInst;
	}

	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public String getUYmd() {
		return this.UYmd;
	}

	public void setUYmd(String UYmd) {
		this.UYmd = UYmd;
	}

	public BigDecimal getULength() {
		return this.ULength;
	}

	public void setULength(BigDecimal ULength) {
		this.ULength = ULength;
	}

	public int getUGs() {
		return this.UGs;
	}

	public void setUGs(int UGs) {
		this.UGs = UGs;
	}

	public BigDecimal getQuantity() {
		return this.quantity;
	}

	public void setQuantity(BigDecimal quantity) {
		this.quantity = quantity;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public BigDecimal getUMjg() {
		return this.UMjg;
	}

	public void setUMjg(BigDecimal UMjg) {
		this.UMjg = UMjg;
	}

	public BigDecimal getLinetotal() {
		return this.linetotal;
	}

	public void setLinetotal(BigDecimal linetotal) {
		this.linetotal = linetotal;
	}

	public String getIssue() {
		return this.issue;
	}

	public void setIssue(String issue) {
		this.issue = issue;
	}

	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public String getDalloc() {
		return this.dalloc;
	}

	public void setDalloc(String dalloc) {
		this.dalloc = dalloc;
	}

	public String getResP() {
		return this.resP;
	}

	public void setResP(String resP) {
		this.resP = resP;
	}

	public String getProRes() {
		return this.proRes;
	}

	public void setProRes(String proRes) {
		this.proRes = proRes;
	}

	public String getImpmeas() {
		return this.impmeas;
	}

	public void setImpmeas(String impmeas) {
		this.impmeas = impmeas;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getUnitMsr() {
		return unitMsr;
	}

	public void setUnitMsr(String unitMsr) {
		this.unitMsr = unitMsr;
	}

	public BigDecimal getNumPerMsr() {
		return numPerMsr;
	}

	public void setNumPerMsr(BigDecimal numPerMsr) {
		this.numPerMsr = numPerMsr;
	}

	public BigDecimal getUGjjg() {
		return UGjjg;
	}

	public void setUGjjg(BigDecimal uGjjg) {
		UGjjg = uGjjg;
	}

}
